### ISSUE TITLE
Getting Final Objective Value

### ISSUE THREAD

**Issue by EtashGuha** [locuslab/mixing#1]
I am trying to evaluate your mixing method on Maxcut. When I run it on a graph, I don't see where the solution is listed in the output. If you could advice, I would appreciate it. All I see are fval, which does not seem to be the optimal value of maxcut.

**Comment by xflash96** [comment]
Hi EtashGuha,

Thanks for your interest in the work!
THe fval is the SDP cut value (negated, since we are doing minimization) listed in p.12 of the paper.
Do you need the discrete vertex assignment instead?

**Comment by EtashGuha** [comment]
I would like to know the size of the cut preferrably.

**Comment by xflash96** [comment]
OK, I've added the randomized rounding feature to the code, and you will now see the CUT size when running MAXCUT.
Note that for better rounding quality, you'll need to increase the number of randomized trials, like "-r 10000" (the larger, the better).
The vertex assignment (+1 or -1) will be in INPUT.rounding.
