### ISSUE TITLE
MAXSAT results and approximation ratio

### ISSUE THREAD

**Issue by trevphil** [locuslab/mixing#3]
Hello! Thanks a lot for making this code public, it's awesome :)

I have a question about the `V` matrix output of MAXSAT, the truth direction (`V[0]`), and randomized rounding.

I'm trying to use the tool in my own project but it looks like `INPUT.sol` is a `(n, k)` shaped matrix where there are `n` literals in the CNF. From what I understand, there should be `n + 1` vectors of length `k` (not `n` as it is now), so the first row in `INPUT.sol` should be the "truth direction" used for randomized rounding.

To solve the issue on my side, I've changed the way that the results are printed by replacing `i < model.n` with `i <= model.n`. This produces a `(n + 1, k)` shaped matrix in `INPUT.sol`.

```
FILE *fout = fopen(fout_name, "w");
    for (int i=0; i<=model.n; i++) {
        for (int j=0; j<model.k; j++)
            fprintf(fout, "%.22g ", model.V[i][j]);
        fprintf(fout, "\n");
    }
    fclose(fout);
```

However, when I apply randomized rounding on these results, **sometimes the approximation ratio is below the lower bound I would expect of `0.878`**. Am I doing something wrong? (Note that _usually_ the approximation ratio is quite good, ~0.98, but occasionally even as low as 0.70 so I don't think it is numerical error).

I am happy to provide code samples if desired. The parsing of the tool's results and randomized rounding are in Python.

**Comment by xflash96** [comment]
Hi Trevor, glad that you're interested in this work!
You're right w.r.t. the output for maxsat... I should have a different output for maxcut & maxsat.
For the rounding, are you using a randomized rounding similar to the "eval_maxsat" function? If so, increasing n_trial (currently only 1) will reduce the variance. Another trick: do multiple trials and record only the best result. This will have a big boost to the ratio.

**Comment by trevphil** [comment]
> For the rounding, are you using a randomized rounding similar to the "eval_maxsat" function? If so, increasing n_trial (currently only 1) will reduce the variance. Another trick: do multiple trials and record only the best result. This will have a big boost to the ratio.

Hi Po-Wei, yes I am indeed using randomized rounding similar to `eval_maxsat` (pick random `r` on unit sphere, compare sign of dot product between `r.dot(V[0])` and `r.dot(V[i]) for i=1...N`. Increasing the number of trials brings the best approximation to almost always 0.98 or more.

**However**, with that said, I thought that for even just 1 trial, the worst-case approximation ratio should be 0.878 based on the work of [Goemans and Williamson](https://klein.mit.edu/~goemans/PAPERS/maxcut-jacm.pdf). Maybe I misread the literature.

**Comment by xflash96** [comment]
Theorem 3.3 of Goemans and Williamson's paper in 1995 is proved in expectation.
Actually, it proves that
> E[cut from randomized rounding from V] >= α * SDP value,

and

> SDP value >= optimal maxcut (continuous opt >= discrete opt.)

That is,

> E[cut from randomized rounding from V] >= α * optimal maxcut.

The "worst-case" mentioned in that paper is for the input graph. It means that for any input graph (not just random graphes), the alpha>0.878 holds for the algorithm.

**Comment by trevphil** [comment]
I see, thank you for the clarification. "Expectation" is an important keyword there. I will close this ticket.

Out of curiosity though, have you ever noticed there seems to be a pattern w.r.t. the angle between the random vector `r` and the truth direction `V[0]` (i.e. `arccos(r.dot(V[0]))`) and the approximation ratio. I've been playing around and sampling `r` such that the angle between `r` and `V[0]` is uniformly distributed between [0, pi]. The results show a consistent pattern, even across different CNF formulas in different problem domains.
![image](https://user-images.githubusercontent.com/12385689/147815443-528a090e-224a-430f-a6a7-d48faafdaae2.png)

Also a quite interesting pattern if you look at the _mean distance_ of the vectors in `V` to the hyperplane whose normal is defined by `r`.
![image](https://user-images.githubusercontent.com/12385689/147815507-97bcf815-df77-49a0-93cd-ebc6723b3361.png)

Can take the discussion offline if desired :)

**Comment by xflash96** [comment]
Nice! I wasn't noticed of the relationship between angle and approximation
ratio,
but there's some literature on skewing the angles to achieve a better
approximation ratio, e.g. RPR2. See this paper
<http://www.cs.cmu.edu/~ninamf/papers/alg-config-colt.pdf> for a survey.
Discussion offline is welcomed. Glad to hear someone working in this
direction.
